spring:
  application:
    name: spring-cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitp-git/fx-data-automation.git
          username: amitp-git
          password: <password>
          search-paths:
            - fx_config

server:
  port: 8999
